image: registry.gitlab.com/adaptivestone/ubuntu-node:latest

stages:
  - install
  - codeStyle
  - test

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 day

prettier:
  stage: codeStyle
  needs:
    - install

  script:
    - npm run codestyle

lint:
  stage: codeStyle
  needs:
    - install

  script:
    - npm run lint

test:
  stage: test
  needs:
    - install

  services:
    - redis:latest
  variables:
    LOGGER_CONSOLE_LEVEL: "error"
    REDIS_URI: redis://redis
  script:
    - npm test
