image: registry.gitlab.com/adaptivestone/ubuntu-node:latest

stages:
  - install
  - codeStyle
  - test

install:
  stage: install
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 day

prettier:
  stage: codeStyle
  script:
    - npm run codestyle

test:
  stage: test
  services:
    - redis:latest
  variables:
    LOGGER_CONSOLE_LEVEL: 'error'
    REDIS_URI: redis://redis
  script:
    - npm test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
