/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Regenerate with: `npm run gen`
 *
 * Source of truth: `Auth.ts`'s `routes` getter and
 * `static get middleware()` Map.
 */

import type GetUserByToken from '../services/http/middleware/GetUserByToken.ts';
import type RateLimiter from '../services/http/middleware/RateLimiter.ts';
import type {
  BaseRequestContext,
  UnionAppInfoProvides,
} from '../services/http/types.ts';
import type { StandardSchemaV1 } from '../services/validate/types.ts';
import type Auth from './Auth.ts';

/**
 * Type-level navigation into the controller's `routes` getter. Schema
 * references for inline schemas resolve through this alias.
 */
type AuthRoutes = InstanceType<typeof Auth>['routes'];

/** Request type for `POST /login` (handler: `postLogin`). */
export type PostLoginRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  > & {
    request: StandardSchemaV1.InferOutput<
      AuthRoutes['post']['/login']['request']
    >;
  };
};

/** Request type for `POST /register` (handler: `postRegister`). */
export type PostRegisterRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  > & {
    request: StandardSchemaV1.InferOutput<
      AuthRoutes['post']['/register']['request']
    >;
  };
};

/** Request type for `POST /logout` (handler: `postLogout`). */
export type PostLogoutRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  >;
};

/** Request type for `POST /verify` (handler: `verifyUser`). */
export type VerifyUserRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  >;
};

/** Request type for `POST /send-recovery-email` (handler: `sendPasswordRecoveryEmail`). */
export type SendPasswordRecoveryEmailRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  > & {
    request: StandardSchemaV1.InferOutput<
      AuthRoutes['post']['/send-recovery-email']['request']
    >;
  };
};

/** Request type for `POST /recover-password` (handler: `recoverPassword`). */
export type RecoverPasswordRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  > & {
    request: StandardSchemaV1.InferOutput<
      AuthRoutes['post']['/recover-password']['request']
    >;
  };
};

/** Request type for `POST /send-verification` (handler: `sendVerification`). */
export type SendVerificationRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<
    readonly [typeof GetUserByToken, typeof RateLimiter]
  > & {
    request: StandardSchemaV1.InferOutput<
      AuthRoutes['post']['/send-verification']['request']
    >;
  };
};
