/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Regenerate with: `npm run gen`
 *
 * Source of truth: `Home.ts`'s `routes` getter and
 * `static get middleware()` Map.
 */

import type GetUserByToken from '../services/http/middleware/GetUserByToken.ts';
import type {
  BaseRequestContext,
  UnionAppInfoProvides,
} from '../services/http/types.ts';

/** Request type for `GET /` (handler: `home`). */
export type HomeRequest = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<readonly [typeof GetUserByToken]>;
};
