/**
 * AST emit integration. Correctness of the *content* is gated by the golden tsc
 * test (`routeTypes.golden.test.ts`, which now runs the AST pipeline and
 * type-checks the output against real handlers); the extraction/resolution units
 * live in `astExtract`/`astResolve`/`astModel`. Here we check the emit + pipeline
 * wiring: every fixture emits via AST with no needsBoot deferral.
 */

import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { noopLogger } from '../helpers/logger.ts';
import type { IApp } from '../server.ts';
import { generateRouteTypesViaAst } from './astEmit.ts';
import { specFromExtracted } from './astSpec.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const controllersDir = path.join(here, '__fixtures__/controllers');
const FIXTURES = ['File', 'Inherited', 'Schemas', 'Advanced'];

describe('astEmit', () => {
  it.each(
    FIXTURES,
  )('resolves %s via the AST path (no needsBoot deferral)', async (name) => {
    // Emitted content is gated by the golden tsc test; here we assert each
    // fixture is statically analyzable through the shared front-end.
    const { resolved } = await specFromExtracted(
      path.join(controllersDir, `${name}.ts`),
    );
    expect(resolved.needsBoot).toBe(false);
  });

  // NOTE: the full pipeline over `__fixtures__/controllers` (discover → write →
  // tsc-check) is exercised by `routeTypes.golden.test.ts` — and ONLY there, so a
  // single test file writes the shared `__fixtures__/*.routes.gen.ts` (two
  // parallel writers raced and flaked the golden tsc gate). Tests here either
  // emit in-memory or write to their own temp dir.

  it('discovers and emits a .js controller (runtime loads .js too)', async () => {
    // The runtime loader (`helpers/files.ts`) accepts .js controllers; codegen
    // must see them too — otherwise they'd be untyped AND missing from the
    // shared bleed registry (silently wrong chains for OTHER controllers).
    const dir = await mkdtemp(path.join(tmpdir(), 'ast-js-ctrl-'));
    try {
      await writeFile(
        path.join(dir, 'Legacy.js'),
        `import Mw from './Mw.js';
export default class Legacy extends Base {
  get routes() { return { get: { '/': this.list } }; }
  static get middleware() { return new Map([['/{*splat}', [Mw]]]); }
}`,
        'utf8',
      );
      // Decoys the runtime loader also skips — must not be discovered:
      await writeFile(path.join(dir, 'Old.gen.js'), 'export {};\n', 'utf8');
      await writeFile(path.join(dir, 'Legacy.test.js'), 'export {};\n', 'utf8');
      const app = {
        logger: noopLogger,
        foldersConfig: { controllers: dir },
        httpServer: null,
      } as unknown as IApp;
      const { written, needsBoot } = await generateRouteTypesViaAst(
        app,
        noopLogger,
      );
      expect(needsBoot).toEqual([]);
      expect(written).toBe(1);
      const gen = await readFile(
        path.join(dir, 'Legacy.routes.gen.ts'), // .js stripped, not Legacy.js.routes.gen.ts
        'utf8',
      );
      expect(gen).toContain('AUTOGENERATED');
      expect(gen).toContain("import type Mw from './Mw.js';");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }, 30_000);

  it('skips colocated .d.ts / .gen.d.ts files (no spurious needsBoot)', async () => {
    // Mirrors the runtime loader: a declaration file next to controllers has no
    // class → would be needsBoot → would throw, blocking ALL codegen. Must be
    // excluded by discovery instead.
    const dir = await mkdtemp(path.join(tmpdir(), 'ast-discover-'));
    try {
      await writeFile(
        path.join(dir, 'Widget.ts'),
        `export default class Widget extends Base {
  get routes() { return { get: { '/': this.list } }; }
}`,
        'utf8',
      );
      // Capitalized declaration files that pass the old (`.ts`-only) filter:
      await writeFile(
        path.join(dir, 'Widget.gen.d.ts'),
        'export type Foo = { a: number };\n',
        'utf8',
      );
      await writeFile(
        path.join(dir, 'Ambient.d.ts'),
        'declare module "x" { export const y: number; }\n',
        'utf8',
      );
      const app = {
        logger: noopLogger,
        foldersConfig: { controllers: dir },
        httpServer: null,
      } as unknown as IApp;
      const { written, needsBoot } = await generateRouteTypesViaAst(
        app,
        noopLogger,
      );
      expect(needsBoot).toEqual([]); // the .d.ts files were NOT discovered
      expect(written).toBe(1); // only Widget.ts
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }, 30_000);
});
