/**
 * AST emit integration. Correctness of the *content* is gated by the golden tsc
 * test (`routeTypes.golden.test.ts`, which now runs the AST pipeline and
 * type-checks the output against real handlers); the extraction/resolution units
 * live in `astExtract`/`astResolve`/`astModel`. Here we check the emit + pipeline
 * wiring: every fixture emits via AST with no needsBoot deferral.
 */

import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { noopLogger } from '../helpers/logger.ts';
import type { IApp } from '../server.ts';
import { emitGenFileViaAst, generateRouteTypesViaAst } from './astEmit.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const controllersDir = path.join(here, '__fixtures__/controllers');
const FIXTURES = ['File', 'Inherited', 'Schemas', 'Advanced'];

describe('astEmit', () => {
  it.each(
    FIXTURES,
  )('emits %s via the AST path (no needsBoot deferral)', async (name) => {
    const ast = await emitGenFileViaAst(
      path.join(controllersDir, `${name}.ts`),
    );
    expect(ast.needsBoot).toBe(false);
    expect(ast.text).toContain('AUTOGENERATED');
  });

  it('generateRouteTypesViaAst discovers + emits every fixture', async () => {
    const app = {
      logger: noopLogger,
      foldersConfig: { controllers: controllersDir },
      httpServer: null,
    } as unknown as IApp;
    const { written, needsBoot } = await generateRouteTypesViaAst(
      app,
      noopLogger,
    );
    expect(needsBoot).toEqual([]);
    expect(written).toBe(FIXTURES.length);
  }, 30_000);

  it('skips colocated .d.ts / .gen.d.ts files (no spurious needsBoot)', async () => {
    // Mirrors the runtime loader: a declaration file next to controllers has no
    // class → would be needsBoot → would throw, blocking ALL codegen. Must be
    // excluded by discovery instead.
    const dir = await mkdtemp(path.join(tmpdir(), 'ast-discover-'));
    try {
      await writeFile(
        path.join(dir, 'Widget.ts'),
        `export default class Widget extends Base {
  get routes() { return { get: { '/': this.list } }; }
}`,
        'utf8',
      );
      // Capitalized declaration files that pass the old (`.ts`-only) filter:
      await writeFile(
        path.join(dir, 'Widget.gen.d.ts'),
        'export type Foo = { a: number };\n',
        'utf8',
      );
      await writeFile(
        path.join(dir, 'Ambient.d.ts'),
        'declare module "x" { export const y: number; }\n',
        'utf8',
      );
      const app = {
        logger: noopLogger,
        foldersConfig: { controllers: dir },
        httpServer: null,
      } as unknown as IApp;
      const { written, needsBoot } = await generateRouteTypesViaAst(
        app,
        noopLogger,
      );
      expect(needsBoot).toEqual([]); // the .d.ts files were NOT discovered
      expect(written).toBe(1); // only Widget.ts
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }, 30_000);
});
