/**
 * Render one controller's metadata + resolved middleware chains into
 * `<File>.routes.gen.ts` text. The output matches the hand-written format
 * shipped in step 1.5 — same import shape, same per-handler `<Method>Request`
 * aliases, same `InstanceType<typeof Controller>['routes']` navigation pattern.
 *
 * Import paths for middleware classes are reused verbatim from the controller's
 * own source file. The gen file lives in the same directory as the controller,
 * so relative paths to siblings (other middleware files, etc.) work without
 * recomputation. Framework types (`BaseRequestContext`, `StandardSchemaV1`)
 * are computed relative to the controller's location.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  ControllerMeta,
  MiddlewareRef,
  RouteMeta,
} from './collectMetadata.ts';

/**
 * Inputs the emit step needs that aren't in the metadata itself.
 *
 * `chains` is parallel to `controller.routes`: chains[i] is the resolved
 * middleware list for routes[i], pre-computed by the caller via
 * `RouteRegistry.flatten()` (single source of truth shared with runtime).
 */
export interface EmitInput {
  controller: ControllerMeta;
  /** Absolute path to the controller's source `.ts` file. */
  srcPath: string;
  /** Resolved middleware chains, parallel to `controller.routes`. */
  chains: MiddlewareRef[][];
}

/** Emit the gen.ts text for one controller. */
export async function emitGenFile(input: EmitInput): Promise<string> {
  const { controller, srcPath, chains } = input;
  const source = await fs.readFile(srcPath, 'utf8');
  const importMap = parseImports(source);

  const uniqueMiddlewares = collectUniqueMiddlewares(chains);

  const frameworkRoot = findFrameworkSrcRoot(srcPath);
  const ctrlDir = path.dirname(srcPath);
  const relFromCtrl = (target: string) => relativeImport(ctrlDir, target);

  const typesPath = relFromCtrl(
    path.join(frameworkRoot, 'services/http/types.ts'),
  );
  const validateTypesPath = relFromCtrl(
    path.join(frameworkRoot, 'services/validate/types.ts'),
  );
  const ctrlBaseName = path.basename(srcPath, '.ts');
  const ctrlImportPath = `./${ctrlBaseName}.ts`;

  const middlewareImports = uniqueMiddlewares
    .map((mw) => {
      const importPath = importMap.get(mw);
      if (!importPath) {
        throw new Error(
          `emit: middleware '${mw}' not found in imports of ${srcPath}. ` +
            `Add an import for it in the controller, or codegen will not be able to type the chain.`,
        );
      }
      return `import type ${mw} from '${importPath}';`;
    })
    .sort();

  const routesAlias = `${controller.className}Routes`;
  const anyRouteHasSchema = controller.routes.some((r) => r.hasSchema);

  const handlerBlocks = controller.routes
    .map((route, i) => renderHandlerType(route, chains[i] ?? [], routesAlias))
    .filter((block) => block !== null);

  const importLines: string[] = [];
  importLines.push(...middlewareImports);
  importLines.push(
    `import type {`,
    `  BaseRequestContext,`,
    `  UnionAppInfoProvides,`,
    `} from '${typesPath}';`,
  );
  if (anyRouteHasSchema) {
    importLines.push(
      `import type { StandardSchemaV1 } from '${validateTypesPath}';`,
    );
    importLines.push(
      `import type ${controller.className} from '${ctrlImportPath}';`,
    );
  }
  const importBlock = importLines.join('\n');

  const routesAliasBlock = anyRouteHasSchema
    ? `\n/**\n * Type-level navigation into the controller's \`routes\` getter. Schema\n * references for inline schemas resolve through this alias.\n */\ntype ${routesAlias} = InstanceType<typeof ${controller.className}>['routes'];\n`
    : '';

  const header = `/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Regenerate with: \`npm run gen\`
 *
 * Source of truth: \`${ctrlBaseName}.ts\`'s \`routes\` getter and
 * \`static get middleware()\` Map.
 */
`;

  return `${header}\n${importBlock}\n${routesAliasBlock}\n${handlerBlocks.join('\n\n')}\n`;
}

/**
 * Build the per-handler `<MethodName>Request` type for one route.
 *
 * Output is intentionally single-line for the union/schema generics —
 * gen files are gitignored, so biome skips them (`vcs.useIgnoreFile`),
 * and TS doesn't care about line length. No formatter post-step needed.
 */
function renderHandlerType(
  route: RouteMeta,
  chain: MiddlewareRef[],
  routesAlias: string,
): string | null {
  if (!route.handlerName) {
    return null;
  }
  const typeName = `${pascalCase(route.handlerName)}Request`;

  const tupleInner =
    chain.length === 0
      ? 'readonly []'
      : `readonly [${chain.map((m) => `typeof ${m.className}`).join(', ')}]`;

  const requestOverride = route.hasSchema
    ? ` & { request: StandardSchemaV1.InferOutput<${routesAlias}['${route.method}']['${route.path}']['request']> }`
    : '';

  return `/** Request type for \`${route.method.toUpperCase()} ${route.path}\` (handler: \`${route.handlerName}\`). */
export type ${typeName} = BaseRequestContext & {
  appInfo: UnionAppInfoProvides<${tupleInner}>${requestOverride};
};`;
}

function collectUniqueMiddlewares(chains: MiddlewareRef[][]): string[] {
  const set = new Set<string>();
  for (const chain of chains) {
    for (const mw of chain) {
      set.add(mw.className);
    }
  }
  return Array.from(set);
}

function pascalCase(name: string): string {
  if (name.length === 0) {
    return name;
  }
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/**
 * Parse top-of-file `import` declarations into a binding-name → path map.
 * Handles default imports (`import X from '…'`), namespace-style default
 * (`import * as X from '…'`), and named imports (`import { A, B as C }
 * from '…'`). Strips `import type` and `as Alias` rebinding.
 */
function parseImports(source: string): Map<string, string> {
  const map = new Map<string, string>();
  const re =
    /import\s+(?:type\s+)?(?:(\w+)\s*,?\s*)?(?:\*\s+as\s+(\w+)\s+)?(?:\{([^}]+)\}\s+)?from\s+['"]([^'"]+)['"]/g;
  let m: RegExpExecArray | null;
  while (true) {
    m = re.exec(source);
    if (m === null) {
      break;
    }
    const [, defaultName, starName, namedBlock, importPath] = m;
    if (defaultName) {
      map.set(defaultName, importPath ?? '');
    }
    if (starName) {
      map.set(starName, importPath ?? '');
    }
    if (namedBlock) {
      for (const piece of namedBlock.split(',')) {
        const trimmed = piece.trim();
        if (!trimmed) {
          continue;
        }
        // `OrigName as LocalName` → bind LocalName
        const asMatch = trimmed.match(/(\w+)\s+as\s+(\w+)/);
        const localName = asMatch
          ? asMatch[2]
          : trimmed.replace(/^type\s+/, '').trim();
        if (localName) {
          map.set(localName, importPath ?? '');
        }
      }
    }
  }
  return map;
}

/**
 * Find the framework's `src/` root by walking up from `srcPath` until we hit
 * a directory whose name is `src`. Used to compute import paths to framework
 * type modules. Falls back to walking up from this file's location.
 */
function findFrameworkSrcRoot(_srcPath: string): string {
  // Use this module's own location to find src/, since we ship inside the
  // framework. `import.meta.url` resolves to .../src/codegen/emit.ts.
  const here = fileURLToPath(new URL('.', import.meta.url));
  // here = .../src/codegen/
  return path.resolve(here, '..');
}

/** Compute a TS-style relative import specifier from `fromDir` to `toFile`. */
function relativeImport(fromDir: string, toFile: string): string {
  let rel = path.relative(fromDir, toFile);
  if (!rel.startsWith('.')) {
    rel = `./${rel}`;
  }
  // Ensure forward slashes (cross-platform)
  return rel.split(path.sep).join('/');
}
