# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check  Types

on:
  push:
    branches: ['*']

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: npm clean install
        run: npm ci
      - run: node --run prettier

  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: npm clean install
        run: npm ci
      - run: node --run lint
